"""initial schema

Revision ID: ebe0cc43e1b4
Revises: 
Create Date: 2025-12-14 11:07:02.598094

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe0cc43e1b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")


    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('last_update', sa.String(length=255), nullable=True),
    sa.Column('seo_meta_description', sa.Text(), nullable=True),
    sa.Column('seo_meta_keywords', sa.String(length=1000), nullable=True),
    sa.Column('seo_meta_viewport', sa.String(length=100), nullable=True),
    sa.Column('seo_meta_charset', sa.String(length=50), nullable=True),
    sa.Column('seo_meta_theme_color', sa.String(length=20), nullable=True),
    sa.Column('seo_meta_application_name', sa.String(length=100), nullable=True),
    sa.Column('seo_meta_thumbnail', sa.String(length=500), nullable=True),
    sa.Column('seo_title_tag', sa.String(length=500), nullable=True),
    sa.Column('seo_canonical', sa.String(length=1000), nullable=True),
    sa.Column('seo_headings', sa.JSON(), nullable=True),
    sa.Column('seo_open_graph', sa.JSON(), nullable=True),
    sa.Column('seo_twitter_cards', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('paragraph_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_author'), 'articles', ['author'], unique=False)
    op.create_index(op.f('ix_articles_paragraph_count'), 'articles', ['paragraph_count'], unique=False)
    op.create_index(op.f('ix_articles_seo_meta_keywords'), 'articles', ['seo_meta_keywords'], unique=False)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.create_index(op.f('ix_articles_word_count'), 'articles', ['word_count'], unique=False)
    op.create_table('article_embedding_1024',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index('article_embedding_1024_idx', 'article_embedding_1024', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_article_embedding_1024_article_id'), 'article_embedding_1024', ['article_id'], unique=True)
    op.create_table('article_paragraphs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_paragraphs_article_id'), 'article_paragraphs', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_paragraphs_order_index'), 'article_paragraphs', ['order_index'], unique=False)
    op.create_table('paragraph_embeddings_1024',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['paragraph_id'], ['article_paragraphs.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'paragraph_id')
    )
    op.create_index(op.f('ix_paragraph_embeddings_1024_article_id'), 'paragraph_embeddings_1024', ['article_id'], unique=False)
    op.create_index(op.f('ix_paragraph_embeddings_1024_paragraph_id'), 'paragraph_embeddings_1024', ['paragraph_id'], unique=False)
    op.create_index('paragraph_embeddings_1024_embedding_idx', 'paragraph_embeddings_1024', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('paragraph_embeddings_1024_embedding_idx', table_name='paragraph_embeddings_1024', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_paragraph_embeddings_1024_paragraph_id'), table_name='paragraph_embeddings_1024')
    op.drop_index(op.f('ix_paragraph_embeddings_1024_article_id'), table_name='paragraph_embeddings_1024')
    op.drop_table('paragraph_embeddings_1024')
    op.drop_index(op.f('ix_article_paragraphs_order_index'), table_name='article_paragraphs')
    op.drop_index(op.f('ix_article_paragraphs_article_id'), table_name='article_paragraphs')
    op.drop_table('article_paragraphs')
    op.drop_index(op.f('ix_article_embedding_1024_article_id'), table_name='article_embedding_1024')
    op.drop_index('article_embedding_1024_idx', table_name='article_embedding_1024', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('article_embedding_1024')
    op.drop_index(op.f('ix_articles_word_count'), table_name='articles')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_seo_meta_keywords'), table_name='articles')
    op.drop_index(op.f('ix_articles_paragraph_count'), table_name='articles')
    op.drop_index(op.f('ix_articles_author'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
